name: first workflow

on:
 push:
  branches:
   - main

jobs:
 exmple-job:
  runs-on: ubuntu-latest

  steps:
     - name: print a message
       run: echo "welcome to our first github actions workflow"

     - name: Checkout repo
       uses: actions/checkout@v6.0.2

     - name: list repo files
       run: ls -la
